import type { EditorThemeClasses } from "lexical";

import "./editor-theme.css";

const theme: EditorThemeClasses = {
  autocomplete: "EditorTheme__autocomplete",
  blockCursor: "EditorTheme__blockCursor",
  characterLimit: "EditorTheme__characterLimit",
  code: "EditorTheme__code",
  codeHighlight: {
    atrule: "EditorTheme__tokenAttr",
    attr: "EditorTheme__tokenAttr",
    boolean: "EditorTheme__tokenProperty",
    builtin: "EditorTheme__tokenSelector",
    cdata: "EditorTheme__tokenComment",
    char: "EditorTheme__tokenSelector",
    class: "EditorTheme__tokenFunction",
    "class-name": "EditorTheme__tokenFunction",
    comment: "EditorTheme__tokenComment",
    constant: "EditorTheme__tokenProperty",
    deleted: "EditorTheme__tokenDeleted",
    doctype: "EditorTheme__tokenComment",
    entity: "EditorTheme__tokenOperator",
    function: "EditorTheme__tokenFunction",
    important: "EditorTheme__tokenVariable",
    inserted: "EditorTheme__tokenInserted",
    keyword: "EditorTheme__tokenAttr",
    namespace: "EditorTheme__tokenVariable",
    number: "EditorTheme__tokenProperty",
    operator: "EditorTheme__tokenOperator",
    prolog: "EditorTheme__tokenComment",
    property: "EditorTheme__tokenProperty",
    punctuation: "EditorTheme__tokenPunctuation",
    regex: "EditorTheme__tokenVariable",
    selector: "EditorTheme__tokenSelector",
    string: "EditorTheme__tokenSelector",
    symbol: "EditorTheme__tokenProperty",
    tag: "EditorTheme__tokenProperty",
    unchanged: "EditorTheme__tokenUnchanged",
    url: "EditorTheme__tokenOperator",
    variable: "EditorTheme__tokenVariable",
  },
  embedBlock: {
    base: "EditorTheme__embedBlock",
    focus: "EditorTheme__embedBlockFocus",
  },
  hashtag: "EditorTheme__hashtag",
  heading: {
    h1: "text-4xl font-bold mb-6 mt-8 text-foreground",
    h2: "text-3xl font-semibold mb-4 mt-6 text-foreground/95",
    h3: "text-2xl font-medium mb-3 mt-5 text-foreground/90",
    h4: "text-xl font-medium mb-3 mt-5 text-foreground/90",
    h5: "text-lg font-medium mb-3 mt-5 text-foreground/90",
  },
  hr: "my-8 border-t border-gradient-to-r from-transparent via-border to-transparent",
  hrSelected: "EditorTheme__hrSelected",
  image: "editor-image",
  indent: "EditorTheme__indent",
  inlineImage: "inline-editor-image",
  layoutContainer: "EditorTheme__layoutContainer",
  layoutItem: "EditorTheme__layoutItem",
  link: "EditorTheme__link",
  list: {
    checklist: "EditorTheme__checklist",
    listitem: "EditorTheme__listItem",
    listitemChecked: "EditorTheme__listItemChecked",
    listitemUnchecked: "EditorTheme__listItemUnchecked",
    nested: {
      listitem: "EditorTheme__nestedListItem",
    },
    olDepth: [
      "EditorTheme__ol1",
      "EditorTheme__ol2",
      "EditorTheme__ol3",
      "EditorTheme__ol4",
      "EditorTheme__ol5",
    ],
    ol: "list-decimal ml-6 mb-4 space-y-1",
    ul: "list-disc ml-6 mb-4 space-y-1",
  },
  ltr: "ltr",
  mark: "EditorTheme__mark",
  markOverlap: "EditorTheme__markOverlap",
  paragraph: "EditorTheme__paragraph",
  quote: "EditorTheme__quote",
  rtl: "rtl",
  specialText: "EditorTheme__specialText",
  tab: "EditorTheme__tabNode",
  table: "EditorTheme__table",
  tableAddColumns: "EditorTheme__tableAddColumns",
  tableAddRows: "EditorTheme__tableAddRows",
  tableAlignment: {
    center: "EditorTheme__tableAlignmentCenter",
    right: "EditorTheme__tableAlignmentRight",
  },
  tableCell: "EditorTheme__tableCell",
  tableCellActionButton: "EditorTheme__tableCellActionButton",
  tableCellActionButtonContainer: "EditorTheme__tableCellActionButtonContainer",
  tableCellHeader: "EditorTheme__tableCellHeader",
  tableCellResizer: "EditorTheme__tableCellResizer",
  tableCellSelected: "EditorTheme__tableCellSelected",
  tableFrozenColumn: "EditorTheme__tableFrozenColumn",
  tableFrozenRow: "EditorTheme__tableFrozenRow",
  tableRowStriping: "EditorTheme__tableRowStriping",
  tableScrollableWrapper: "EditorTheme__tableScrollableWrapper",
  tableSelected: "EditorTheme__tableSelected",
  tableSelection: "EditorTheme__tableSelection",
  text: {
    bold: "EditorTheme__textBold",
    capitalize: "EditorTheme__textCapitalize",
    code: "bg-accent/80 px-2 py-1 rounded-md text-sm font-mono border shadow-sm",
    highlight: "EditorTheme__textHighlight",
    italic: "EditorTheme__textItalic",
    lowercase: "EditorTheme__textLowercase",
    strikethrough: "EditorTheme__textStrikethrough",
    subscript: "EditorTheme__textSubscript",
    superscript: "EditorTheme__textSuperscript",
    underline: "EditorTheme__textUnderline",
    underlineStrikethrough: "EditorTheme__textUnderlineStrikethrough",
    uppercase: "EditorTheme__textUppercase",
  },
};

export default theme;
